PROGPLAT_ARCH         =arm8
PROGPLAT_PARAMS       =cache_multiw
PROGPLAT_BOARD        =rpi3
PROGPLAT_RUN_TIMEOUT  =60000
__PROGPLAT_MUL_RUNS__ =0
__PROGPLAT_MEM_DEF_1__  =expmem_byte_to_word(0)
MEASUREMENT           =cache
